-- +goose Up
-- +goose StatementBegin
CREATE TYPE "services" AS ENUM (
  'traffic_flow',
  'air_quality',
  'power_consumption',
  'water_levels',
  'waste_management',
  'structural_integrity'
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_contributed_sensors" (
  "contribution_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "service" services NOT NULL,
  "service_sensor_id" int NOT NULL,
  "contributed_at" timestamp DEFAULT (now())
);

ALTER TABLE "user_contributed_sensors" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE "user_contributed_sensors" DROP CONSTRAINT "user_contributed_sensors_user_id_fkey";
DROP TABLE "user_contributed_sensors";
DROP TABLE "users";
DROP TYPE "services";
-- +goose StatementEnd
